apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
  namespace: argo
spec:
  generators:
  - list:
      elements:
#        - cluster: local-cluster
#          app-name: prometheus
#          chart: kube-prometheus
#          targetRevision: 9.0.3
#          repoURL: 'https://charts.bitnami.com/bitnami'
#          namespace: monitoring
#        - cluster: local-cluster
#          app-name: thanos
#          chart: thanos
#          targetRevision: 15.0.4
#          repoURL: 'https://charts.bitnami.com/bitnami'
#          namespace: monitoring
#        - cluster: home-cluster-raspi
#          app-name: grafana
#          chart: grafana
#          targetRevision: 7.3.7
#          repoURL: 'https://grafana.github.io/helm-charts'
#          namespace: monitoring
#        - cluster: home-cluster-raspi
#          app-name: prometheus
#          chart: kube-prometheus
#          targetRevision: 9.0.3
#          repoURL: 'https://charts.bitnami.com/bitnami'
#          namespace: monitoring
#        - cluster: home-cluster-rke
#          app-name: prometheus
#          chart: kube-prometheus
#          targetRevision: 9.0.3
#          repoURL: 'https://charts.bitnami.com/bitnami'
#          namespace: monitoring
        - cluster: home-cluster-rke 
          app-name: neuvector
          chart: core
          targetRevision: 2.7.7
          repoURL: 'https://neuvector.github.io/neuvector-helm/'
          namespace: cattle-neuvector-system
        - cluster: home-cluster-rke
          app-name: nv-monitor
          chart: monitor
          targetRevision: 2.7.7
          repoURL: 'https://neuvector.github.io/neuvector-helm/'
          namespace: cattle-neuvector-system
  template:
    metadata:
      name: '{{cluster}}-{{app-name}}'
      namespace: argo
    spec:
      project: default
      sources:
        - repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          helm:
            valueFiles:
              - '$values/applications/{{cluster}}/{{app-name}}/values.yaml'
          chart: '{{chart}}'
        - repoURL: 'https://github.com/rajeshkio/my-lab-setup.git'
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: true
