{
 "title": "NeuVector",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(nv_summary_hosts,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NeuVector Product Links",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center\">\n  \n  ![NeuVector Logo](https://avatars.githubusercontent.com/u/19367275?s=200&v=4)<br>\n  <br>\n  [Documentation](https://open-docs.neuvector.com)<br>\n  </br>\n  [Users Slack Channel](https://rancher-users.slack.com/archives/C036F6JDZ8C)<br>\n  </br>\n  [GitHub](https://github.com/neuvector)\n\n</div>"
   }
  },
  {
   "title": "Enforcer Replica Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nv_summary_enforcers{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CVE Database Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_summary_cvedbVersion{cluster=\"$cluster\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Discovered Pod Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_summary_pods", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Controller CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(nv_controller_cpu{cluster=\"$cluster\"}) by (display)\n",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Denied Admissions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_admission_denied{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Controller Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nv_summary_controllers{cluster=\"$cluster\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Disconnected Enforcers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_summary_disconnectedEnforcers{cluster=\"$cluster\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Security Event Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "nv_log_events{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Controller Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(nv_controller_memory{cluster=\"$cluster\"}) by (display)",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Cluster CVE Count",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nv_container_vulnerabilityHigh{cluster=\"$cluster\"}) by (service)"
    },
    {
     "expr": "sum(nv_container_vulnerabilityMedium{cluster=\"$cluster\"}) by (service)"
    }
   ]
  },
  {
   "title": "Enforcer CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(nv_enforcer_cpu{cluster=\"$cluster\"}) by (display)\n",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Vulnerabilities by Service",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 3, "y": 14 },
   "targets": [
    {
     "expr": "sum(nv_container_vulnerabilityHigh{cluster=\"$cluster\"}) by (exported_service)"
    },
    {
     "expr": "sum(nv_container_vulnerabilityMedium{cluster=\"$cluster\"}) by (exported_service)"
    }
   ]
  },
  {
   "title": "Registry Images Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "sum(nv_image_vulnerabilityHigh{cluster=\"$cluster\"}) by (name)"
    },
    {
     "expr": "sum(nv_image_vulnerabilityMedium{cluster=\"$cluster\"}) by (name)"
    }
   ]
  },
  {
   "title": "Enforcer Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(nv_enforcer_memory{cluster=\"$cluster\"}) by (display)",
     "legendFormat": "{{display}}"
    }
   ]
  }
 ]
}